-   id: gocheckcov
    name: 'go gocheckcov'
    entry: run-gocheckcov.sh
    #files: '\.go$'
    files: '^.*_(test|stub)\.go'
    language: 'script'
    description: "Runs `gocheckcov`, requires golang"